USE TestsDB
GO

CREATE TABLE UserInfos (
	id INT PRIMARY KEY IDENTITY,
	firstName NVARCHAR(20) NOT NULL,
	lastName NVARCHAR(20) NOT NULL,
	birth DATE
);
GO

CREATE TABLE Accounts (
	id INT PRIMARY KEY IDENTITY,
	[login] VARCHAR(20) NOT NULL,
	[password] VARCHAR(20) NOT NULL
);
GO

CREATE TABLE Results (
	id INT PRIMARY KEY IDENTITY,
	score INT NOT NULL
);
GO

CREATE TABLE Quizs (
	id INT PRIMARY KEY IDENTITY,
	[name] NVARCHAR(20) NOT NULL
);
GO


CREATE TABLE TestsCategories (
	id INT PRIMARY KEY IDENTITY,
	[name] NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE Tests (
	id INT PRIMARY KEY IDENTITY,
	[name] NVARCHAR(20) NOT NULL
);
GO

CREATE TABLE Questions (
	id INT PRIMARY KEY IDENTITY,
	text NVARCHAR(50) NOT NULL
);
GO

CREATE TABLE Answers (
	id INT PRIMARY KEY IDENTITY,
	text NVARCHAR(30) NOT NULL
);
GO